on:
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:
  build_wheel:
    name: build Python wheel
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.12'
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install poetry && poetry install
    - name: Get version number
      if: github.event_name == 'release'
      uses: actions/github-script@v4
      id: get_version
      with:
        script: |
          const tag = context.ref.substring(10)
          const no_v = tag.replace('v', '')
          core.setOutput('no-v', no_v)
    - name: Set version on release
      if: github.event_name == 'release'
      run: poetry version ${{steps.get_version.outputs.no-v}}
    - name: Build wheel
      run: poetry build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-wheel
        path: dist/*.whl
    - name: Upload release artifact
      uses: softprops/action-gh-release@v2
      if: github.event_name == 'release'
      with:
        files: dist/*.whl